services:
  runner:
    build:
      context: .
      dockerfile: docker/dev.runner.Dockerfile
    working_dir: /app/packages/runner
    environment:
      - BUCKET_URL=http://minio:9000
      - BUCKET_ACCESS_KEY=minioadmin
      - BUCKET_SECRET_KEY=minioadmin
      - BUCKET_NAME=origan
      - BUCKET_REGION=us-east-1
      - WORKERS_PATH=/workers
      - EVENTS_NATS_SERVER=nats://nats:4222
    volumes:
      - runner_workers:/workers
      - ./packages/runner:/app/packages/runner
    command: ["start", "--port", "8000", "--ip", "0.0.0.0", "--main-service", "/app/packages/runner/functions/supervisor", "--event-worker", "/app/packages/runner/functions/event-worker"]
    networks:
      origan-network:
        ipv4_address: 172.20.0.20

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: origan-root
      POSTGRES_PASSWORD: origan
      POSTGRES_DB: origan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      origan-network:
        ipv4_address: 172.20.0.30

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # The entrypoint command is used to create the bucket and set up the MinIO client
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/.minio.sys/buckets;
      /usr/bin/minio server --console-address ':9001' /data &
      sleep 3;
      /usr/bin/mc alias set myminio http://localhost:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/origan --ignore-existing;
      wait"
    volumes:
      - minio_data:/data
    networks:
      origan-network:
        ipv4_address: 172.20.0.40

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-sd", "/data", "-m", "8222", "--store_dir", "/data/jetstream"]
    volumes:
      - nats_data:/data
    networks:
      origan-network:
        ipv4_address: 172.20.0.50

  # This is used to catch the webhook from GitHub
  # Note: Update target to http://host.docker.internal:9999/github/webhook when running control-api locally
  smee:
    image: deltaprojects/smee-client
    command: smee --url https://smee.io/origaneulocal-8MVxlEzBDRVUKj --target http://host.docker.internal:9999/github/webhook
    networks:
      origan-network:
        ipv4_address: 172.20.0.60

networks:
  origan-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  minio_data:
  postgres_data:
  runner_workers:
  nats_data:
